import Head from 'next/head';
import BestSeller from '../components/HomePage/BestSeller';
import BuisnessSummery from '../components/HomePage/BuisnessSummery';
import Carousel from '../components/HomePage/Carousel';
import Categories from '../components/HomePage/Categories';
import ContactInfo from '../components/HomePage/ContactInfo';
import Recommended from '../components/HomePage/Recommended';
import Tesimonials from '../components/HomePage/Tesimonials';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Super pets | a trusted platform to get you super cool pets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Carousel />
        <Categories />
        <Recommended />
        <BestSeller />
        <BuisnessSummery />
        <Tesimonials />
        <ContactInfo />
      </main>
    </div>
  )
}
